name: "Lint Commit Messages"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
            perf
            ci
            revert

          subjectPattern: ^[A-Z].+\s[A-Z]+-[0-9]+$

          subjectPatternError: |
            The PR title does not match the required format!
            
            ✅ Correct Example:
            "feat: Add user login page OR-25"
            
            ❌ Incorrect Examples:
            "feat: add user login" (Lowercase subject, no ticket)
            "feat: Add user login" (Missing ticket)
            "feat: Add user login OR-25 #done" (Extra text after ticket)

          validateSingleCommit: true